name: 'RSS Parser'
description: 'GitHub Action to Parse RSS Feeds and take action'
inputs:
  github_token:
    description: "GitHub Token. This is only required if the script_output is set to issue."
    required: true
    default: ${{ github.token }}
  feed_url:
    description: "URL of RSS feed to be read"
    required: true
    default: 'https://github.blog/feed/'
  script_output:
    description: "Output of the script (e.g. issue, json, pull_request)"
    required: true
    default: 'issue'
  subfolder:
    description: "Subfolder (used when pull_request mode is set)"
    required: false
  extension:
    description: "File extension (used when pull_request mode is set)"
    required: false
    default: '.social'
  branch_prefix:
    description: "Branch Prefix (used when pull_request mode is set)"
    required: false
    default: 'twitter'
  last_parsed_file:
    description: "Filename to be used for the last parsed file (used when pull_request mode is set)"
    required: false
    default: '.github/last-parsed.json'
outputs:
  posts: 
    description: 'The JSON output of the posts discovered'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'rss'  
  color: 'orange'
