name: "Manual RSS Feed Test"
on:
  workflow_dispatch:
    inputs:
      feed_url:
        description: "URL of RSS feed to be read"
        type: string
        required: true
        default: 'https://github.blog/feed/'
      script_output:
        description: "Output of the script (e.g. issue, json, pull_request)"
        type: string
        required: true
        default: 'issue'
      subfolder:
        description: "Subfolder (used when pull_request mode is set)"
        type: string
        required: false
        default: 'twitter'
      extension:
        description: "File extension (used when pull_request mode is set)"
        type: string
        required: false
        default: '.tweets'
      branch_prefix:
        description: "Branch Prefix (used when pull_request mode is set)"
        type: string
        required: false
        default: 'twitter'
      last_parsed_file:
        description: "Filename to be used for the last parsed file (used when pull_request mode is set)"
        type: string
        required: false
        default: '.github/last-parsed.json'
jobs:
  manual_rss_feed_execution:
    runs-on: ubuntu-latest
    steps: 
      - uses: chrisreddington/rss-parser-action@main
        with:
          feed_url: ${{ inputs.feed_url }}
          script_output: ${{ inputs.script_output }}
          subfolder: ${{ inputs.subfolder }}
          extension: ${{ inputs.extension }}
          branch_prefix: ${{ inputs.branch_prefix }}
          last_parsed_file: ${{ inputs.last_parsed_file }}
