name: "Manual RSS Feed Test"
on:
  workflow_dispatch:
    inputs:
      feed_url:
        description: "URL of RSS feed to be read"
        type: string
        required: true
        default: 'https://github.blog/feed/'
      script_output:
        description: "Output of the script (e.g. issue, json)"
        type: string
        required: true
        default: 'issue'
      subfolder:
        description: "Subfolder (used when pull_request mode is set)"
        type: string
        required: false
        default: 'twitter'
      extension:
        description: "File extension (used when pull_request mode is set)"
        type: string
        required: false
        default: '.tweets'
      branch_prefix:
        description: "Branch Prefix (used when pull_request mode is set)"
        type: string
        required: false
        default: 'twitter'
jobs:
  manual_rss_feed_execution:
    runs-on: ubuntu-latest
    steps: 
      - uses: chrisreddington/rss-parser-action@main
        with:
          feed_url: ${{ inputs.feed_url }}
          script_output: ${{ inputs.script_output }}
